spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guanxiaonan/xuanhuang-houduan.git
          searchPaths: /mirco_service_xuanhuang_config
          username: guanxiaonan
          password: ghguan174910
      label: master
# profiles:
#   active: native
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    lease-renewal-interval-in-seconds: 50     #客户端每隔多少秒发送心跳给服务器端,表明客户端还活着
    lease-expiration-duration-in-seconds: 30  #eureka-server在该时间内没有收到服务的心跳,就会判定该服务失效
# /info 显示对应信息
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
#security:
#  user:
#    name: config
#    password: 123456




