spring:
  application:
    name: gyn-agriculturalData-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://101.201.71.184:3306/iot_nydp?useSSL=false
    username: root
    password: 123456
server:
  port: 9107
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/






