spring:
  application:
    name: gyn-inventory-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/dmx?useSSL=false
    username: root
    password: 123456

server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/






