spring:
  application:
    name: gyn-monitor-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/xuanhuang?useSSL=false
    username: root
    password: 123456
server:
  port: 9106
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/







